name: coi
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - pip
  - pip:
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - seaborn
    - tqdm
    - pyyaml
    - imbalanced-learn
    - joblib 