data:
  raw_path: './data/raw/'
  processed_path: './data/processed/ckd_merged_data_for_modeling.csv'
  month_count: 24

model:
  input_dim: 36
  output_dim: 1
  emb_dim: 64
  hidden_dim: 128
  dropout: 0.2
  learning_rate: 0.001
  batch_size: 128
  max_seq_len: 50
  n_epochs: 100
  patience: 7
  device: cuda

hyperparameters:
  emb_dim: [16, 32, 64]
  hidden_dim: [32, 64, 128]
  learning_rate: [0.001, 0.0001]
  batch_size: [128]
  dropout: [0.0, 0.2, 0.4]

tuning:
  n_epochs: 50
  
paths:
  save_path: './models/'
  results_path: './Outputs/'