data:
  processed_x_path: ./mimic-iv-3.1/processed/X_mimiciv_parallel.npy
  processed_y_path: ./mimic-iv-3.1/processed/y_mimiciv_parallel.npy
  raw_path: ./mimic-iv-3.1/
  
hyperparameters:
  batch_size:
    - 32
    - 64
    - 128
  dropout:
    - 0.1
    - 0.2
    - 0.3
  hidden_dim:
    - 64
    - 128
    - 256
  learning_rate:
    - 0.0001
    - 0.001
    - 0.01
  num_layers:
    - 1
    - 2
    - 3

model:
  type: bilstm
  input_dim: 15
  hidden_dim: 128
  num_layers: 2
  output_dim: 1
  dropout: 0.2
  learning_rate: 0.001
  batch_size: 64
  n_epochs: 200
  patience: 10

paths:
  results_path: ./Outputs/saved_models/
  save_path: ./Outputs/saved_models/

tuning:
  n_epochs: 200 