data:
  processed_path: ./data/mimic-iv-3.1/processed/X_mimiciv_parallel.npy
  label_path: ./data/mimic-iv-3.1/processed/y_mimiciv_parallel.npy
  raw_path: ./data/mimic-iv-3.1/

hyperparameters:
  batch_size:
    - 32
    - 64
    - 128
  dropout:
    - 0.1
    - 0.2
    - 0.3
  hidden_dim:
    - 128
    - 256
    - 512
  learning_rate:
    - 0.0001
    - 0.001
    - 0.01
  num_heads:
    - 1
    - 2
    - 4
  calibration_dim:
    - 32
    - 64
    - 128

model:
  type: adacare
  input_dim: 15
  hidden_dim: 256
  num_heads: 2
  output_dim: 1
  dropout: 0.2
  calibration_dim: 64
  learning_rate: 0.001
  batch_size: 64
  n_epochs: 500
  patience: 10

paths:
  results_path: ./results/mimic/
  save_path: ./results/mimic/

tuning:
  n_epochs: 500