data:
  processed_path: ./data/ckd_data/processed/ckd_merged_data_for_modeling.csv
  month_count: 24

hyperparameters:
  batch_size:
    - 32
    - 64
    - 128
  dropout:
    - 0.1
    - 0.2
    - 0.3
  hidden_dim:
    - 64
    - 128
    - 256
  learning_rate:
    - 0.0001
    - 0.001
    - 0.01
  num_stages:
    - 3
    - 4
    - 5
  kernel_size:
    - 3
    - 5
    - 7

model:
  type: stagenet
  input_dim: 37
  hidden_dim: 128
  output_dim: 1
  num_stages: 4
  kernel_size: 3
  dropout: 0.2
  learning_rate: 0.001
  batch_size: 64
  n_epochs: 500
  patience: 10

paths:
  results_path: ./results/ckd/
  save_path: ./results/ckd/

tuning:
  n_epochs: 500